name: Create and publish Spilo Image with custom configuration scripts

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "branch, tag or SHA"
        required: true

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: junminahn/spilo

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        env:
          BASE_IMAGE: registry.opensource.zalan.do/acid/spilo-14:2.1-p5
        with:
          context: .
          push: true
          tags: ${{ github.event.inputs.ref}}
          labels: spilo-experiment
          build-args: BASE_IMAGE=${{ env.BASE_IMAGE }}
